version: "3.8"

services:
  my-app:
    image: sadgecko/wp:last
    ports:
      - "80:80"
    depends_on:
      - my-mysql
    networks:
      my-wordpress:

  my-mysql:
    image: mysql:8.0
    volumes:
      - wordpress-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: pass
    networks:
      my-wordpress:

  my-monitoring:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      my-wordpress:

volumes:
  wordpress-mysql:

networks:
  my-wordpress: